package com.pc.cxf.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2016-12-22T15:09:18.981+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://server.cxf.pc.com/", name = "HelloCXFService")
public interface HelloCXFService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "helloCXF", targetNamespace = "http://server.cxf.pc.com/", className = "com.pc.cxf.client.HelloCXF")
    @WebMethod
    @ResponseWrapper(localName = "helloCXFResponse", targetNamespace = "http://server.cxf.pc.com/", className = "com.pc.cxf.client.HelloCXFResponse")
    public String helloCXF(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "byeCXF", targetNamespace = "http://server.cxf.pc.com/", className = "com.pc.cxf.client.ByeCXF")
    @WebMethod
    @ResponseWrapper(localName = "byeCXFResponse", targetNamespace = "http://server.cxf.pc.com/", className = "com.pc.cxf.client.ByeCXFResponse")
    public String byeCXF();
}
